version: '3'
services:
  node:
    build:
      context: .
      args:
        APP_DIR: ${APP_DIR}
    environment:
      - NODE_ENV=production
    container_name: apollo_universal_starter
    tty: true
    stdin_open: true
    volumes:
      - ./:${APP_DIR}
      - ${APP_DIR}/build
      - ${APP_DIR}/node_modules
      - /home/node/.cache/yarn
    working_dir: ${APP_DIR}
    user: node
    command: >
       sh -c '
       NODE_ENV=development yarn &&
       (test -f prod-db.sqlite3 || yarn seed) &&
       yarn build &&
       node build/server
       '
    ports:
      - 8080:8080
