spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:apollo
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
#  mail:
#    host: EMAIL_HOST
#    port: 587
#    username: EMAIL_USER
#    password: EMAIL_PASSWORD
#    sender: EMAIL_SENDER # todo: no such property in Spring, need to handle manually
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
graphql:
  servlet:
    async-mode-enabled: true
    exception-handlers-enabled: true
    cors:
      allowed-origins: "*"
      allow-credentials: true
    subscriptions:
      apollo:
        keep-alive-enabled: false
      websocket:
        path: /graphql
graphiql:
  enabled: true
  endpoint:
    subscriptions: /graphql
  mapping: /graphiql
  headers:
    Authorization: Bearer generated-token

jwt:
  secret: "676918AB4D29BFE59CCB943F3C09F5CC8FB3A8511E23E502B67DE95AB9A9D00C"
  access-token-expiration-in-sec: 3600
  refresh-token-expiration-in-sec: 604800